snr_min: 1
snr_max: 5
#n_snr: 300
n_snr: 300
radius_gt: 10
iou_thresh: 0
n_bins: 30
erode: 1
dilation_t: 1
offset_t: 0
window_size: 4
#save_output: true
save_output: false
verbose: false
max_iter: null
labels_pred_method: "contiguous"
run_name: ${name}
sep_max: 1.38
main_threshold: 5.0
max_threshold: null
#use_amp: ${train.ff.params.use_amp}
use_amp: false
